services:
  whisper:
    build: .
    
    ports:
      - "${PORT}:${PORT}"

    container_name: whisper
  
    restart: unless-stopped

    environment:
      - PYTHON_ENV=production
      - HF_TOKEN=${HF_TOKEN}
      - PORT=${PORT}
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE}
      - WHISPER_MODEL_DEVICE=${WHISPER_MODEL_DEVICE}
      - WHISPER_COMPUTE_TYPE=${WHISPER_COMPUTE_TYPE}
    